application: netbootme
version: live
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /(menu.c32|vesamenu.c32)
  static_files: static/\1
  upload: static/(menu.c32|vesamenu.c32)

- url: /googleaf282d669d99b844.html
  static_files: static/googleaf282d669d99b844.html
  upload: static/googleaf282d669d99b844.html

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /tasks/.*
  script: request.py
  login: admin

- url: /.*
  script: request.py
