application: netbootme
version: live
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: (/(?:[a-zA-Z][a-zA-Z0-9]*/)*)(menu.c32|vesamenu.c32)
  static_files: static/\2
  upload: static/(menu.c32|vesamenu.c32)

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /tasks/.*
  script: request.py
  login: admin

- url: /.*
  script: request.py
